title: Shift Maker
description: >-
  Convert shift schedule tables to event lists and vice versa, with custom coloring for different people.
baseurl: "shift-maker/"
url: ""

# Build settings
theme: minima
